#!/usr/bin/env ruby

require "go_time"

unless ARGV.empty?
  puts GoTime.convert(ARGV.join(" "), exception: true)
  exit
end

loop do
  print "> "
  str = gets.chomp
  exit if str == "exit"
  begin
    puts "=> #{GoTime.convert(str, exception: true)}"
  rescue ArgumentError => e
    puts "\e[33m#{e}\e[0m"
  end
end
